first version of documentation
apigear-io/template-qtcpp pull request #23
Opened 2023-03-14 19:55 UTC by dorotaphanSiili

2023-03-22 19:02 UTC, w4bremer requested changes
- Good first version!
- I am not a native speaker, so there are certainly better solutions than my proposals
- Just take the feedback and think about what needs to be changed, I don't expect all my comments to be taken as is :)
- Maybe one or two more screenshots will make it look less technical(boring). e.g. for the QtCreator environment config or so

2023-03-22 19:03 UTC, w4bremer requested changes
- Good first version!
- I am not a native speaker, so there are certainly better solutions than my proposals
- Just take the feedback and think about what needs to be changed, I don't expect all my comments to be taken as is :)
- Maybe one or two more screenshots will make it look less technical(boring). e.g. for the QtCreator environment config or so

2023-03-30 08:20 UTC, dorotaphanSiili commented on docs/docs/features/qmlplugin.md
> +When building and running with *qt creator* the may also need to add `QML_IMPORT_PATH` and `QML2_IMPORT_PATH` also for run environment project settings, even if the settings are using build environme
I'd leave that, it states that normally - within the qt there should be no need to set them, but if it still doesn't work you should add it 🤔

2023-03-30 18:47 UTC, dorotaphanSiili commented on docs/docs/features/olink.md
> +- OlinkClient - the client, that serves your [interface client adapters](olink#Olink-Client-Adapter).
OlinkClient holds a message queue for messages while the connection is offline ? 
Yes - but only if connection was once established and object was linked. Same behavior in cpp template.
I guess we should discuss it. I may remove it from documentation? or it should be left as long as the behavior is not changed?

2023-04-04 11:18 UTC, w4bremer approved these changes

2023-04-05 07:39 UTC, merged